sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mohit/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mohit/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'Docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-167948571635'
  bucket_path: 'Docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
