sudo: required
services:
  - docker
  
before_install:
  - docker build -t Mohit1504/docker-react -f Dockerfile.dev .
  
script:
  - docker run Mohit1504/docker-react npm run test -- --coverage
  
  
